config/routes.rb
Rails.application.routes.draw do
  resources :fictional_things
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fictional_thing.rb
class FictionalThing < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fictional_things_controller.rb
class FictionalThingsController < ApplicationController
  before_action :set_fictional_thing, only: [:show, :edit, :update, :destroy]

  # GET /fictional_things
  # GET /fictional_things.json
  def index
    @fictional_things = FictionalThing.all
  end

  # GET /fictional_things/1
  # GET /fictional_things/1.json
  def show
  end

  # GET /fictional_things/new
  def new
    @fictional_thing = FictionalThing.new
  end

  # GET /fictional_things/1/edit
  def edit
  end

  # POST /fictional_things
  # POST /fictional_things.json
  def create
    @fictional_thing = FictionalThing.new(fictional_thing_params)

    respond_to do |format|
      if @fictional_thing.save
        format.html { redirect_to @fictional_thing, notice: 'Fictional thing was successfully created.' }
        format.json { render :show, status: :created, location: @fictional_thing }
      else
        format.html { render :new }
        format.json { render json: @fictional_thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fictional_things/1
  # PATCH/PUT /fictional_things/1.json
  def update
    respond_to do |format|
      if @fictional_thing.update(fictional_thing_params)
        format.html { redirect_to @fictional_thing, notice: 'Fictional thing was successfully updated.' }
        format.json { render :show, status: :ok, location: @fictional_thing }
      else
        format.html { render :edit }
        format.json { render json: @fictional_thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fictional_things/1
  # DELETE /fictional_things/1.json
  def destroy
    @fictional_thing.destroy
    respond_to do |format|
      format.html { redirect_to fictional_things_url, notice: 'Fictional thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fictional_thing
      @fictional_thing = FictionalThing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fictional_thing_params
      params.require(:fictional_thing).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fictional_things_helper.rb
module FictionalThingsHelper
end

app/views/fictional_things/_form.html.erb
<%= form_for(fictional_thing) do |f| %>
  <% if fictional_thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fictional_thing.errors.count, "error") %> prohibited this fictional_thing from being saved:</h2>

      <ul>
      <% fictional_thing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fictional_things/edit.html.erb
<h1>Editing Fictional Thing</h1>

<%= render 'form', fictional_thing: @fictional_thing %>

<%= link_to 'Show', @fictional_thing %> |
<%= link_to 'Back', fictional_things_path %>

app/views/fictional_things/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fictional Things</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fictional_things.each do |fictional_thing| %>
      <tr>
        <td><%= fictional_thing.title %></td>
        <td><%= link_to 'Show', fictional_thing %></td>
        <td><%= link_to 'Edit', edit_fictional_thing_path(fictional_thing) %></td>
        <td><%= link_to 'Destroy', fictional_thing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fictional Thing', new_fictional_thing_path %>

app/views/fictional_things/new.html.erb
<h1>New Fictional Thing</h1>

<%= render 'form', fictional_thing: @fictional_thing %>

<%= link_to 'Back', fictional_things_path %>

app/views/fictional_things/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @fictional_thing.title %>
</p>

<%= link_to 'Edit', edit_fictional_thing_path(@fictional_thing) %> |
<%= link_to 'Back', fictional_things_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp9127</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>